name: Name and Emai retrieve
on:
  workflow_dispatch:
  


jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check Collaborator Status
        id: is-collaborator
        run: |
          username=${{ env.GITHUB_ACTOR }}
          is_collaborator=false
          for collaborator in ${{ github.repository_collaborators }}
          do
            if [ "$username" = "$collaborator" ]; then
              is_collaborator=true
              break
            fi
          done
          echo "::set-output name=is-collaborator::$is_collaborator"
      - name: Perform Workflow Actions
        if: steps.is-collaborator.outputs.is-collaborator == "true"
        run: |
          echo "true"

