name: Example Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'dev'

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variables
        run: |
          if [ "${{ github.event.inputs.environment }}" == "dev" ]; then
            export envvalue=dev_value
          elif [ "${{ github.event.inputs.environment }}" == "qa" ]; then
            export envvalue=qa_value
          elif [ "${{ github.event.inputs.environment }}" == "prod" ]; then
            export envvalue=prod_value
          else
            echo "Invalid environment specified."
            exit 1
          fi

      - name: Use environment variable in the job
        run: |
          echo "Using envvalue: $envvalue"
