name: Hello

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to build the Docker image for'
        required: true
        options: ${{ steps.get_branches.outputs.branches }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code for the specified branch
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      # Build and push Docker image to ECR
      # ...

      # Deploy Docker image to ECS
      # ...

      # Step to get the list of branches dynamically
      - name: Get branches
        id: get_branches
        run: |
          branches=$(git ls-remote --heads origin | awk '{print $2}' | awk -F '/' '{print $3}' | sort | uniq)
          echo "::set-output name=branches::$(echo "$branches")"
