on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to build the Docker image for'
        required: true
        type: choice
        choices: ${{ join(github.ref_namespaces, '\n') }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code for the specified branch
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}
      
      # Build and push Docker image to ECR
      # ...

      # Deploy Docker image to ECS
      # ...
