on:
  workflow_dispatch:
    inputs:
      my_choice:
        description: 'Select an option'
        required: true
        options: # list of available options
          - 'Option 1'
          - 'Option 2'
          - 'Option 3'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Display selection
        run: echo "You selected ${{ github.event.inputs.my_choice }}"
